### ISSUE TITLE
css 模块怎么办

### ISSUE THREAD

**Issue by 534591395** [PeterMu/gulp-alias-combo#3]
项目中，我每个web模块的 css 都是 require的，这个情况怎么提取css。

**Comment by PeterMu** [comment]
由于无论是 requirejs 还是 seajs 都是通过插件的实现的 require css，目前暂时不能支持 require css 这种情况。可以写一段 js 胶水代码，去动态加载css（动态插入link），然后再 require 这个 js 模块。
