### ISSUE TITLE
我又来提issue了：当require是相对路径的时候，不支持同目录解析

### ISSUE THREAD

**Issue by sunlanlisa** [PeterMu/gulp-alias-combo#5]
如果我请求的是一个相对路径，不合并的时候，请求路径变成了baseUrl+dialog.css的形式，实际上这个文件是和目前js同一个目录
define(function(require){
    require("./dialog.css");
})

需要写成相对于baseUrl路径才正确
require("gmu/dialog/src/dialog.css");

如果能同目录解析就好了😁~~

**Comment by PeterMu** [comment]
配置上 supportRelative 为 true 时，可以支持相对路径的合并，遗憾的是不支持非 js 文件的合并，require 的文件必须是 js 文件。css 文件建议单独加载。

**Comment by sunlanlisa** [comment]
恩，后来考虑也是单独加载了。
